global T_LIST, T_COORDINATES, D_THRESHOLD, B_AREA, RESULT_LIST,PLUS_INDEX,TIMESTAMP, T_TIMESTAMP, INITIAL_T_LOC, INITIAL_Z

T_LIST = [(0,0)]
T_COORDINATES = [(0,0,0,0)]
D_THRESHOLD = 50
B_AREA = 45000
RESULT_LIST = []
PLUS_INDEX = 0
TIMESTAMP = 0
T_TIMESTAMP = [0]
INITIAL_T_LOC = []
INITIAL_Z = []


